### ISSUE TITLE
How to use this repository.

### ISSUE THREAD

**Issue by yashwant121** [oschaaf/envoy-perf-vscode#1]
I am new to Envoy, and I wish to use your repo to run envoy with vscode.
Please help me to get started with installation. 
Thank you.

**Comment by oschaaf** [comment]
Hi, these days, Envoy is facilitating vscode usage itself:
https://github.com/envoyproxy/envoy/pull/11207

It might be worth asking around over at the #envoy-dev channel on Slack how to best leverage that.  I think this repository is used solely by me for development on envoyproxy/nighthawk; now that Envoy is facilitating vscode useage itself, I'd recommend against taking this as a starting point (unless you'd want to work on Nighthawk).

**Comment by yashwant121** [comment]
Thank you so much.
